= Автоматическая рассылка уведомление клиентам банка о завершении срока действий их банковских карт

== Техническое задание

Разработать задание по расписанию, которое будет осуществлять рассылку уведомления клиентам при завершении срока действия банковской карты.
Предусмотреть следующие функции:

1. Создание клиента. Если клиент уже был раннее заведен, возвращать его идентификатор, чтобы избежать дублей
2. Создание карты: заводить новую карту клиенту, проверяя уникальность номера карты при заведении.
3. Аннулирование карты. Закрывает действующую карту клиента.

== Особенности реализации:

1. Сделать spring-boot с rest api.
2. Задание по расписанию должно не просто уведомлять клиента, а генерировать автоматически новую карту.
3. Рассылка уведомлений должна производиться на почту по расписанию.
4. Реализовать абстракцию над хранением клиентских данных, чтобы можно было менять реализацию хранения клиентских данных с HashMap, на БД.
5. Ходить в БД через Spring Data JPA.
6. Покрыть юнит и интеграционными тестами.

