spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/card_db?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: postgres
#    driverClassName: